# Generated by Django 4.2 on 2023-05-04 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='alternative_id',
        ),
        migrations.AddField(
            model_name='medication',
            name='alternatives',
            field=models.ManyToManyField(blank=True, to='project.medication'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 21, 8, 16, 93655, tzinfo=datetime.timezone.utc)),
        ),
    ]
