# Generated by Django 4.2 on 2023-05-18 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='price',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pharmacist',
        ),
        migrations.AddField(
            model_name='prescriptionmedication',
            name='dosage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 17, 5, 36, 54, 389501, tzinfo=datetime.timezone.utc)),
        ),
    ]
