# Generated by Django 4.2 on 2023-05-04 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_medication_alternative_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 21, 11, 44, 898500, tzinfo=datetime.timezone.utc)),
        ),
    ]
